<?
$siteprefix="/development/";
$sitename="PPCIS development";
$sitelogo="ppcis.jpg";
$logourl="http://www.ppcis.org/";
$stylesheet="ppcis.css";
//$stylesheet="intranet-test.css";
$news_notify="";
$support_notify="";
$backwards_history=FALSE;
$auto_authorise_news=FALSE;
$file_store="/var/tmp/intranet/files/";
$use_mail=FALSE;
$db_hostname="localhost";
$db_username="intranet";
$db_password="appdata";
$db_name="intranet_devel";
?>
