<br>
<br>
To add an item to a list, type a new name into the blank
box at the top and click "Add new".  To rename an item,
re-type its name and then click the "Rename" button
immediately to its right.  To delete an item, click the
"Delete" button immediately to its right.<br>
<br>
You must be careful.  You will not be asked for
confirmation of any of your actions.  Bearing in mind
that each item in the list is represented internally by
a unique number, care must be taken when deleting items.
If you delete an item, everything that was associated
with it will not be associated with anything in the list
any more.  Even if you create a new item with the same
name, it'll have a new unique number, and the system will
not treat it as the same thing.<br>
<br>
It's worth noting that you can only rename one thing at
a time.  If you attempt to rename several items, only the
one nearest the "Rename" button that you clicked will
actually be changed.
