<h1>Configuring the colour scheme</h1>

In this screen, you can specify the colour scheme that you wish
to use for PPCIS.  The default greys can be changed to any
colour that you wish, by specifying the values as valid HTML
colour definitons (such as <b>red</b> or <b>#FF0000</b>).<br>
<br>
To make the changes, click the "Change colour scheme" button.
Changes are made immediately across the entire system.<br>
<?require("settings_save.inc");?>
