<h1>User manager - delete a user</h1>

This is a confirmation page.  If you click the <b>Delete user</b>
button, then this user will be removed from the system.  Their
internal directory entry will be removed, and their rights will
be removed also, to prevent these right being accidentally
inherited by a future user.<br>
<br>
The revoking of rights has immediate effect, as it always does.
If the user you are deleting is still logged in, however, they
will still be able to use the system with the privileges of a
normal user until they log out or close their browser.  As their
directory entry will be removed, they will <i>not</i> be able to
access any files in the library that have a team access list.
