<h1>User manager - listing</h1>

This page shows every user on the system.<br>
<br>
At a glance, you can see the user's login name, and their real
name.<br>
<br>
Clicking any of the letters of the alphabet along the top
will filter the entire list so that the only names you see
are those whose surname begins with that letter.  This is
functionally the same as typing their initial into the "Last name"
box and clicking the Search button.<br>
<br>
The "First name" and "Last name" boxes can be used to find a
specific person.  Simply type the required names or parts of names
in and click the Search button.  The list of names will be filtered to show
only those names beginning with what you type into those boxes.<br>
<br>
The directory column lets you add/remove/edit a user's directory details by
clicking the word "modify".
