<h1>External directory - listing</h1>

This page lists all of the people and organisations stored in the external
directory.  Unlike the internal directory, the contacts in the external
directory do not have an account on the intranet system.<br>
<br>
Like the internal directory, you can search on first name or last name.  In
addition to this, you can also search by company.  Clicking the letters of the
alphabet will search for all contacts whose last name begins with that letter.
You can also filter on the type of contact, by choosing a type from the
drop-down list.<br>
<br>
The list is sorted by company name, unless you search by surname, in which it is sorted by surname.<br>
<br>
Clicking on the email link will start an email to the contact, and clicking the
details link ill show you more information about that contact.
