<h1>External directory admin - edit contact</h1>

This extremely simple form allows you to edit the details of
this external contact.  Simply fill in each field with the
relevant information (where known) and click <b>Submit changes</b>.<br>
<br>
Clicking the <b>Delete this record</b> button at the bottom
will erase the details of this external contact from the
directory.  If you are creating a new contact, this button
will have no effect apart from clearing the form.
