<h1>External directory admin - listing</h1>

This screen lists all of the external contacts stored in the
external directory.  It is filterable on first name, last
name, company or contact type.  The list is in company order
unless filtered only on last name, when it is in last name
order.<br>
<br>
Clicking the word <b>Edit</b> in the right hand column will
allow you to edit or remove that contact's details.  Clicking
the word <b>NEW</b> at the top of that column will allow you
to type in the details of a new contact.
