<h1>FAQ admin - modify an existing FAQ</h1>

This page allows you to edit the contents of the FAQ
that you clicked on in the FAQ admin page.  You can
choose a new category from it, edit the question and
edit the answer if necessary.<br>
<br>
Clicking the <b>Modify FAQ number <i>n</i></b> button will
update the FAQ with your new changes.<br>
Clicking the <b>Delete FAQ number <i>n</i></b> button will
remove the question and its answer from the system
completely.
