<h1>Library - file details (adjust mode)</h1>

This screen shows the details of this file.  Displayed here are
the file name, its unique number, its size, its mime type (which
determines which application will be run if you open this file)
and a description of the file, if one was given.  There is also
a list of the teams which are allowed to access this file, or
the words "This file is not restricted" if there have been no
team restrictions placed.<br>
<br>
To rename this file, type in a new name and click <b>Make changes</b>.<br>
To move this file, type in the unique number of the folder you want
to move it into, and click <b>Make changes</b>.  <i>If the number you
type is of a folder that does not exist, the file will only be
accessible by zooming directly to its unique number.  There is
currently no checking made, so make sure you type in a valid number.</i><br>
<br>
Here you can also make changes to the security of a file.  By selecting
teams from the drop down list, and clicking the <b>Add team to secure
list</b>, you cause the file to be restricted only to the teams which
are listed.  Users who are not in the team will be unable to download
or open this file.  If all the teams listed are removed by clicking
the <b>Remove this team from access list --&gt;</b> buttons, the file
will become open and unrestricted.<br>
<br>
To delete this file completely, tick the confirmation box and then
click the <b>Delete this file</b> button.<br>
<br>
At the bottom of the page there are two boxes where you can type
in the unique number of any file or any folder, and zoom directly
to that file or folder.<br>
<br>
<i>If you are a files administrator, you can click the "Adjust
this file" link to make alterations to this file.</i>
