<h1>Library - file listing</h1>

This is the file storage module.  At the top of the page is a
representation of the library's file system, starting with the
Filesystem Root.  There, you can see any parent folders (folders
in which the current folder is contained) and also any child
folders (folders which are contained within the current folder).
Clicking on any of these folders will make that folder the current
folder.<br>
<br>
Below this is the name of the current folder, and its unique
number, followed by a list of any files contained within this
folder.  If there are no files, the words "Folder is empty" will
be shown.<br>
<br>
If there are files, each will be displayed as a row in a table,
showing the name and the size.  There will also be shown links to
save or open the file, if you have access to the file.<br>
<br>
At the end of the row is a link that will take you to a page
showing more detailed information about the file.<br>
<br>
At the bottom of the page there are two boxes where you can type
in the unique number of any file or any folder, and zoom directly
to that file or folder.<br>
<br>
<i>If you are a files administrator, there will be a form here
which you can use to upload a new file into this folder.  You can
browse for the file, and type in a description at the same time.
Clicking Send will upload the file.  You will also notice a link
to adjust this folder, which can be used to make changes.</i>
