<h1>Library - file details</h1>

This screen shows the details of this file.  Displayed here are
the file name, its unique number, its size, its mime type (which
determines which application will be run if you open this file)
and a description of the file, if one was given.  There is also
a list of the teams which are allowed to access this file, or
the words "This file is not restricted" if there have been no
team restrictions placed.<br>
<br>
To download this file to your computer, click the Download link.<br>
To open this file in a new window, click the Open link.<br>
<i>These links are only available if you have access to this file.</i><br>
<br>
At the bottom of the page there are two boxes where you can type
in the unique number of any file or any folder, and zoom directly
to that file or folder.<br>
<br>
<i>If you are a files administrator, you can click the "Adjust
this file" link to make alterations to this file.</i>
