<h1>Library - file search</h1>

This is the library's file search screen.  You can enter any number
of search terms into the fields presented.  Words entered in the
filename field will be matched against the file's name, those in the
synopsis field will matched agains the file's description.<br>
<br>
If there are files matching your search, each will be displayed as
a row in a table, showing the name and the size.  There will also
be shown links to the file's details page, and the folder in which
it is stored.  If you do not have access to the file, the file name
will appear in <i>italics</i>.<br>
<br>
At the end of the row is a link that will take you to a page
showing more detailed information about the file.<br>
