<h1>Library - file listing (adjust mode)</h1>

This is the file storage module.  At the top of the page is a
representation of the library's file system, starting with the
Filesystem Root.  There, you can see any parent folders (folders
in which the current folder is contained) and also any child
folders (folders which are contained within the current folder).
Clicking on any of these folders will make that folder the current
folder.<br>
<br>
Below this is the name of the current folder, and its unique
number, followed by a list of any files contained within this
folder.  If there are no files, the words "Folder is empty" will
be shown.  Here you can enter a new name for this folder, and you
can also move this folder into a different location by typing in
the unique number of the folder you want it moving into.  This
has no effect on the Filesystem Root folder.  <b>Beware that if
you attempt to move a folder into itself, or into one of its child
folders, or into a non-existent folder, you will lose access to
the folder.</b>  In this event, it is still possible to zoom
directly to a lost folder if you know its unique number.<br>
<br>
You can also add new child folders by typing in a new name in the
box to the right of the button marked "Add new folder" and then
clicking that button.<br>
<br>
If there are files, each will be displayed as a row in a table,
showing the name and the size.  There will also be shown links to
save or open the file, if you have access to the file.<br>
<br>
At the end of the row is a link that will take you to a page
showing more detailed information about the file.<br>
<br>
At the bottom of the page there are two boxes where you can type
in the unique number of any file or any folder, and zoom directly
to that file or folder.<br>
<br>
There is a form here which you can use to upload a new file
into this folder.  You can browse for the file, and type in a
description at the same time.  Clicking Send will upload the file.
