<h1>Frequently Asked Questions</h1>

By default, this page displays every frequently asked question
that's been recorded on the helpdesk system, with the associated
answer.<br>
<br>
You can filter the frequently asked questions by choosing a
category from the drop-down list, and by typing in a word or
part of a word into the "Word search" text box and then
clicking filter.<br>
<br>
If you know the unique number of a frequently asked question,
you can type it in directly to the "FAQ number" text box, and
then click filter.  If you put a number in this box, the
system will ignore the other filter options.
