<h1>Call manager - logging a new call</h1>

This page is where you can log a new call to the helpdesk system.
You can choose a call type and a call location.  The call location
defaults to the location recorded in your directory entry, if any.<br>
<br>
Below this is a text box where you can log your call.  Please feel
free to add as much information as is relevant, as helpdesk staff
will be better able to deal with your call if they have as much
information as possible.<br>
<br>
Once your call is logged, you will receive a unique number.  This
number can be used in all communication with the helpdesk staff,
and they will be able to access the history of your call from the
system much more quickly if you do.<br>
<br>
The call will appear in your list of calls, so you can easily
follow the progress being made, and add new information etc at
a later time.
