<h1>Submit a new news article</h1>

On this page, you can compose a new item of news.<br>
<br>
Type in a headline, and choose a suitable topic from the list.
The list of available topics is chosen by the system's news
admin staff.<br>
<br>
For the main text body of the article, you can type freely in
the article text box.  Any returns you type will be kept in,
and you can even format your text using the HTML tags for italic
and for bold:<br>
<br>
&lt;I&gt;This is in italics&lt;/I&gt;<br>
&lt;B&gt;This is in bold&lt;/B&gt;<br>
<br>
This would look like:<br>
<I>This is in italics</I><br>
<B>This is in bold</B><br>
<br>
Your article can be previewed by clicking the submit button.  You
will see your article appear at the bottom of the page as it will
eventually appear on the news page.  You can edit the article as
many times as you like.<br>
<br>
Once you are happy with your news article, you can submit it to one
of the system's news admin staff by ticking the box near the bottom
of the page and then clicking submit.<br>
<br>
Your article will not appear immediately, but will go into a queue
to be authorised by a news admin.  They have the ability to edit
your news article before they authorise it.
