<h1>News administration</h1>

This page allows news admins to edit and delete news articles.
When a news article is submitted, it comes to this page to
await the authorisation of a news admin before being displayed
on the front page.  Articles that have not yet been authorised
have the submitter's name displayed in italics and in brackets
like <i>[John Smith]</i>.  Those that have been authorised show
the submitter's name in the default text format.<br>
<br>
If you click on the word <b>DETAILS</b> against any article,
the page re-loads with some extra content.  Firstly, you will
see the article as it currently stands, and as it will look on
the front page if authorised.<br>
<br>
You can edit the article below, including altering the headline,
the body of the news, the URL (if applicable) and the topic it
will be displayed with for filtering.  You can use
&lt;i&gt;italics&lt;/i&gt; and &lt;b&gt;bold&lt;/b&gt; HTML tags
for <i>italics</i> and <b>bold</b> text formatting.<br>
<br>
Clicking the authorise button on its own will not authorise the
article, but will instead just renew the page with the updated
article being previewed at the top.  This way, you can edit and
preview the article until you are happy with it.<br>
<br>
An important note here - there will be no evidence that the
article has been altered by a news admin unless they make that
clear in their editing.<br>
<br>
To authorise the article, tick the box that indicates that you
are happy with the article, then authorise.  It will appear on
the news page in the correct place depending on when the original
user submitted it.  <i>If you wait a long time to authorise an
article, it is quite possible that it will be authorised directly
into the archive</i>.<br>
<br>
If you wish to dispose of the article completely, tick the box
that indicates that you wish to delete the article, and then
authorise.
