<h1>Archived news articles</h1>

This page displays all the articles before the most recent 10.
It is the counterpart to the page with the current news articles.<br>
<br>
The filtering is done before the counting.  If you don't filter,
you get the articles from 11 articles ago and before.  If you
filter on a specific topic, you get everything before the most
recent 10 articles in that topic.<br>
<br>
When there are more than 30 archived news articles, a pager
appears, allowing you to skip forwards and backwards through
the articles thirty at a time.<br>
<br>
When you want to view one of the older articles, click the word
VIEW at the right of the article's headline.  The article will
appear in its original form, at the top of the page.  You can
still see the headlines of the other articles below.
