<h1>Current news articles</h1>

This page displays the ten most recent articles on the intranet system by default.
You can choose a news topic from the drop-down list and click Filter to display the
last ten news articles in any given topic.  If an article is more than ten articles
old, it will appear in the "archived news articles" section.<br>
<br>
When you use the filter feature, some articles that would normally be considered
archived will be displayed on this page, because the article is less than ten
articles old when you only look at the filtered articles.
