<h1>User manager - create new user</h1>

This screen allows you to create a new user account on the system.
The username is mandatory.  The other fields are optional, but
bear in mind that an empty password is a security hole, and without
a name some of the activities of the user will appear without that
name, resulting in incomplete sentences such as "Submitted by."<br>
<br>
The password must be entered twice, as a precaution against mis-types.
The username must be unique on the system.  If you attempt to re-use
an existing username, the user will not be created.
