<h1>Altering your directory entry</h1>

This page allows you to alter your details that
appear in the internal directory.
<br>
Clicking the "Save these values to directory for user
<i>n</i>" button will create your directory entry, if
there isn't one already, and will put the contents of
this page into it.<br>
<br>
The title should be something like Mr, Mrs, Ms, Dr,
etc. rather than your job title.<br>
<br>
The first name and last name will be used in all the
normal interfaces in the system - identifying the
submitter of a news article, following helpdesk calls,
even the title bar has this information placed there.<br>
<br>
The email address field can be left blank.  If an address
is entered here, a link will be created on your directory
details page and the main directory listing screen,
allowing users to start an email to you with one
click.<br>
<br>
The telephone and mobile telephone numbers, in addition
to being displayed on your details page, are shown on
the main directory screen.<br>
<br>
The post field is intended to be your job title.
Anything can be typed in here.<br>
<br>
The location field is a drop-down list.  If there are
no locations defined, there won't be any real choices to
be made here.  If the location that this you are in is
deleted, it will revert to "Nowhere".<br>
<br>
For security reasons, you cannot change your team.  If
your team is incorrect, you will need to contact one of
the administrators of the system.
<br>
The line manager field is a drop-down list of all the
users on the system.  If the manager's account is
deleted from the system, the manager field will revert
to "Nobody".<br>
