<h1>Change your password</h1>

Here, you can change your password.  It's important to do
this from time to time.  If other people learn your password,
they can log helpdesk calls and submit articles under your
name.  They can access files that might be confidential.
They can access any administrative privileges that you have.<br>
<br>
When you pick a new password, try to make it difficult for
people to guess.  Using your own name, or that if a loved
one, is not recommended.  Using words written down on posters
or objects around your place of work is also not recommended.
These are all things that somebody trying to guess your password
would try.<br>
<br>
When you have a new password to enter, put your old password in
the CURRENT password box and then type your new password
carefully in both the NEW password boxes.  Click the "Set your
password" button to make the change.<br>
<br>
If you get your current password wrong, or mis-type your new one,
no changes will happen.
