<h1>User manager - rights administration</h1>

This page lets you grant and revoke rights to users.
Simply choose the desired rights, and click the save
button.  The granting and revoking of rights has an
immediate effect on the user if they are logged in.<br>
<br>
A user admin has access to:
<ul>
<li>   User Manager</li>
<li>   New User</li>
<li>   Teams and Locations</li>
</ul>
A news admin has access to:
<ul>
<li>   News admin</li>
<li>   News topics</li>
</ul>
A directory admin has access to:
<ul>
<li>   Directory Admin</li>
<li>   External directory admin</li>
<li>   Teams and locations</li>
<li>   Website admin</li>
<li>   Website and contact categories</li>
</ul>
A helpdesk staff has access to:
<ul>
<li>   Helpdesk categories</li>
<li>   Teams and Locations</li>
</ul>
Also, helpdesk staff admin have great control over the
state of calls logged on the helpdesk, and can add, edit
and remove frequently asked questions.<br>
<br>
A file store admin has the ability to create, rename
and remove folders and files from the library.  They
can also grant and revoke the team access controls on
files in the library.
