<h1>User manager - directory editing</h1>

This page allows you to alter the details that appear
in the internal directory for a given user.  The
internal directory only contains information associated
with users, but does not have to contain information
about all the users, or even any of them.<br>
<br>
The first name and last name are special.  They will
be retained even if you remove somebody's directory
details.  Everything else will be lost if you click
the "Remove all directory details for user <i>n</i>"
button.<br>
<br>
Clicking the "Save these values to directory for user
<i>n</i>" button will create a directory entry, if there
isn't one already, and will put the contents of this
page into it.<br>
<br>
The title should be something like Mr, Mrs, Ms, Dr,
etc. rather than their job title.<br>
<br>
The first name and last name will be used in all the
normal interfaces in the system - identifying the
submitter of a news article, following helpdesk calls,
even the title bar has this information placed there.<br>
<br>
The email address field can be left blank.  If an address
is entered here, a link will be created on the user's
directory details page and the main directory listing
screen, allowing users to start an email to this person
with one click.<br>
<br>
The telephone and mobile telephone numbers, in addition
to being displayed on the user's details page, are shown
on the main directory screen.<br>
<br>
The post field is intended to be the user's job title.
Anything can be typed in here.<br>
<br>
The location and team fields are drop-down lists.  The
lists can be edited in the "Teams and locations" page.
If there have been no teams or locations defined, there
won't be any real choices to be made here.  If the team
and location that this user is in are deleted, they will
revert to "Alone" and "Nowhere", respectively.<br>
<br>
The line manager field is a drop-down list of all the
users on the system.  If the manager's account is
deleted from the system, the manager field will revert
to "Nobody".<br>
<br>
<b>To change an ex-directory user's name without them
being in the directory, you must first change their name
and click the Save button, then you must delete the
automatically created directory entry with the Remove
button.  The name will remain changed, and the user
will be ex-directory.</b>
