<h1>User manager - change username and password</h1>

This page lets you change both the user's username and their password.
As each user is defined by a unique number, the username does not have
to be a fixed value.  Because it is used to log in, though, it does
need to be unique.<br>
<br>
Here you can either change the user's password, or both the username
<i>and</i> the password.  At this time it is not possible to change
the username without also changing the password.<br>
<br>
Some checking is done.  Blank or duplicate usernames and passwords
that aren't typed the same way twice will all be rejected.
