<?require("help/viewcalldetail.inc");?><br>
<br>
As a member of the helpdesk staff, you are able to alter most of the
call's information.  To change the owner, priority, category or location
simply select new values from the drop-down lists, and click <b>Apply changes</b>.<br>
<br>
You can assign support staff to calls.  To do this, choose their name
from the drop down list of helpdesk staff, tick the check box, and
click <b>Apply changes</b>.  That member of staff will receive an email
from the system letting them know that you have assigned them to the call.<br>
<br>
To remove staff, tick the check box by their name and then click
<b>Apply changes</b>.  You can only remove one person from a call at a time.<br>
<br>
If you have been assigned to a call, you can mark yourself as active
or inactive by selecting the option near your name.  What this means exactly
is down to how you choose to run a helpdesk; it has no effect on the
operation of the helpdesk other than to show <i>currently active</i> next
to your name when others view the call.<br>
<br>
You can also add history to calls.  To add history to this
call, type the information that you wish to add into the text box
towards the bottom of the page, and then click <b>Apply changes</b>.<br>
<br>
If you wish to close this call, tick the box at the bottom of the page
and then click <b>Apply changes</b>.<br>
<br>
If you click on "Discard all changes and refresh page" the page will re-load,
updating itself with any changes that might have been made, and getting rid
of any changes you might have made before clicking the <b>Apply changes</b>
button.
