<h1>Call manager - listing</h1>

On this page, you can see a list of all of the calls that you have
logged on the helpdesk call management system.  They are listed in
order of priority.<br>
<br>
If you have any calls logged, you will see a table showing you a few
details of each one:
<ul>
<li>The call's unique number</li>
<li>The owner of the call (this will be you)</li>
<li>The date that the call was logged (and whether it was in the morning or afternoon)</li>
<li>The priority of the call</li>
<li>The call's category</li>
<li>The call's location</li>
<li>The first few words of the original call text</li>
</ul>
<br>
Clicking on the unique number of a call will take you to a screen
where you can follow the progress of the call, and where you can
can add additional information.<br>
<br>
At the top of the page there are two drop-down lists where you can
filter the list of calls by category and location.  There is also
a box where you can directly type in the number of a call, and go
straight to that call's information screen.<br>
<br>
Using this feature, you can view the details of any call on the
system - not just the ones that you have logged yourself.
