<?require("help/viewcalldetail.inc");?><br>
<br>
As the owner of this call, you are able to alter the location of the call.
To do this, simply select a new location from the drop-down list of
locations, and click <b>Apply changes</b>.<br>
<br>
You can also add history to calls that you own.  To add history to this
call, type the information that you wish to add into the text box
towards the bottom of the page, and then click <b>Apply changes</b>.<br>
<br>
If you wish to close your call, tick the box at the bottom of the page
and then click <b>Apply changes</b>.<br>
<br>
If you click on "Discard all changes and refresh page" the page will re-load,
updating itself with any changes that might have been made, and getting rid
of any changes you might have made before clicking the <b>Apply changes</b>
button.
