<h1>Web links directory admin</h1>

On this page there is one row of text boxes for each web link
currently stored in the web links directory.  At the top, there
is also a blank row of text boxes which can be used to add a
new web link.<br>
<br>
The <i>name</i> column contains a name for the link.  It is
this name that the user will click on to use the link.  The
<i>URL</i> column contains the URL of that link.  It will be
displayed in such a manner that it can be selected for copying.
The <i>description</i> column should contain a few words
describing what the link is, in case it isn't obvious from the
name.  Finally, the <i>category</i> column contains a drop-down
list of all the categories, which the user can use to filter
the list of web links.<br>
<br>
To alter the contents of a web link, edit the contents of the
text boxes on that row, then click the <b>Update</b> button on
that row.<br>
<br>
To remove a web link from the directory, click the <b>Delete</b>
button on that row.<br>
<br>
To create a new link, fill in the blank row at the top, and click
the <b>Add new</b> button.
